name: backend CI

on:
  push:
    branches-ignore: [master, development, staging]
    paths: [backend/**]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: cd backend && yarn install --immutable

      - name: Run tests
        run: cd backend && yarn run ci-test
 