name: Run tests on push to feature branches if changes to client_web

on:
  push:
    branches-ignore: [master, development, staging]
    paths: [client_web/**]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: cd client_web && yarn install --immutable
      - run: yarn test
