name: client_web CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run client_web tests
        if: always() 
        run: cd client_web && yarn run ci-test

      - name: Run backend tests
        if: always()
        run: cd backend && yarn run ci-test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        if: always()
        with:
          files: reports/*.xml
          report_individual_runs: "true"
