name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI/*']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Report tests
      uses: dorny/test-reporter@v1.5.0
      with:
        artifact: test-output # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: 'reports/*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit